apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: db
spec:
  serviceName: "mysql-headless"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: mysql
      project: expense
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: geethaprudhvi/mysql:{{ .Values.statefulset.imageVersion }}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: expense
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" #storage class for dynamic provisioning
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}