apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  type: ClusterIP
  selector: #labels are used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: {{ .Values.service.targetPort }} #pod port